### ISSUE TITLE
Proposal: Improve Key Derivation scheme

### ISSUE THREAD

**Issue by 1ma** [gzuuus/nostr_startr#2]
## Choice of Algorithm

Scrypt is generally considered a better Key Derivation function than PBKDF2[^1][^2], and is also available in the [cryptography module](https://cryptography.io/en/latest/hazmat/primitives/key-derivation-functions/#scrypt).

## Salt

I think it would be better to use a random salt for each key instead of always using a well-known salt embedded in the code. Of course, if we do this we must use the same salt the next time we want to decrypt the same key, so it must be stored. Since nostr_startr already creates a startr_config.json file we could store all scrypt parameters with the encrypted private key:

```json
{
    "pubkey": "...",
    "user": "...",
    "pkey": "...",
    "scrypt": {
        "salt": "vD0RmzebeCQDPKjwBPmxBuJ67bEqTA1QybAc35-70oY=",
        "n": 16384,
        "r": 8,
        "p": 1
    }
}
```

These correspond to the parameters of the Scrypt constructor. If we store them all you can change the defaults later on in the code without breaking existing config files.

### First Run

```
1. Generate or read new Nostr Private Key

2. Generate new salt. This gives 32 random bytes:
>>> salt_for_storage = Fernet.generate_key()               # urlsafe base64
>>> salt = base64.urlsafe_b64decode(salt_for_storage)      # raw bytes
 
4. Init Scrypt with default parameters (to be determined, except length. Fernet wants a URL-safe base64-encoded 32-byte key):
>>> kdf = Scrypt(salt=salt, length=32, n=default_n, r=default_r, p=default_p)

5. Derive key for Fernet with the user's password:
>>> key = base64.urlsafe_b64encode(kdf.derive(b"muh passw0rd"))

6. Use key to encrypt the Nostr Private Key with Fernet and store everything in JSON, including:
  salt_for_storage
  default_r
  default_n
  default_p
```

### Next Runs (startr_config.json present)

```
1. Read everything from json

2. Decode salt:
>>> salt = base64.urlsafe_b64decode(json_salt)

3. Init Scrypt and derive key
>>> kdf = Scrypt(salt=salt, length=32, n=json_n, r=json_r, p=json_p)
>>> key = base64.urlsafe_b64encode(kdf.derive(b"muh passw0rd"))

4. Try to decrypt Nostr Private Key with Fernet and proceed or fail.
```

[^1]: https://en.wikipedia.org/wiki/PBKDF2#Alternatives_to_PBKDF2
[^2]: https://cryptography.io/en/latest/hazmat/primitives/key-derivation-functions/#pbkdf2

**Comment by gzuuus** [comment]
Thanks! now the key derivation scheme its scrypt instead of PBKDF2 and salt its now saved into de json config file
