### ISSUE TITLE
UX: incorrect password prompt

### ISSUE THREAD

**Issue by niclaz** [gzuuus/nostr_startr#7]
When selecting option `1. Start nostr_console` the UI adds a few lines:

```
-------------------*STARTR*-------------------
User: nostr_startr
Pubkey: 20960fb4f3b58fa9296b8193103c39fb4aa198a7d36df1f6642ac7bf53319e41
Password: 

```

If the user typos a password, it cancels the login and return to the homescreen. 

If the user does not notice the change they they sought (startr splash image) they may just type it out again on screen.

Proposal to have a prompt with y/n option asking user if they want to re-try the password or go to home. 

Better user experience and more aligned with webapp flows

**Comment by gzuuus** [comment]
suggestion included in the [new commit](https://github.com/gzuuus/nostr_startr/commit/6e407dde4193a8112bfaf1f865734e686ca80ce5#diff-c544c472b8d83789f11d3de457a53d987e7c6a0d867ce64554884fc64e08bf94)
