### ISSUE TITLE
Linux: Installation process needs an additional step

### ISSUE THREAD

**Issue by niclaz** [gzuuus/nostr_startr#8]
Attempted to run a fresh install of nostr_startr on a Linux distro

Following the readme.md file I realise it is missing a step to add the executable permission to the nostr_console that has been downloaded by the python script.

I doubt this can be done within the .py as it is a permission escalation at the system level. The command is listed in the update process further down `chmod +x "nostr_console_binary_file"` and it is an intuitive to linux power users but maybe not by all.

**Suggestion** Adding a step or separate process in the install for linux users in readme.md where they need to download the `nostr_console` zip for their architecture nd make it executable before someone starts nostr_startr for the first time, to avoid program crash as I experienced today.

**Comment by gzuuus** [comment]
As long as the user running startr is the owner of the downloaded file (nostr_console_file) no privilege escalation is needed to make it executable. 

At this point startr allows you to install and give execution permissions to nostr_console automatically when it does not detect any nostr_cosole binaries. Even if you select to launch nostr_console without having previously downloaded nostr_console, also the `install/update nostr_console` option in the menu does this.

However, you made me realise that it would be good to include `u+x` to the `chmod` statement in startr to avoid conflicts in more permission-limiting environments and only give execution permissions to the current executing user and not to everyone (`a+x` vs `u+x`).

This way the additional step in the installation process is not necessary, however I will include it as an optional step.
